### ISSUE TITLE
Twitter trace value size

### ISSUE THREAD

**Issue by hoaaosnw** [dmemsys/Anole#1]
https://github.com/dmemsys/Anole/blob/c04f8d381b297b95f1e7d17eb1c48fd358b4213d/experiments/workload.cc#L437

As shown in the code, all value size in twitter trace is sizeof(int), i.e. 4 bytes, why?

**Comment by bernardshen** [comment]
We calculate the size of the cache as the number of cached objects and use uniform size (256B) for cached objects. The size assigned in the line of code doesn't affect the size of the cached object because the size of cached objects is controlled by the `block_size` field in the configuration files, e.g., `experiments/configs/client_conf_sample_adaptive.json`, which is set to 256B.
